'use client'


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 output.glb --transform --draco
Files: output.glb [1.58MB] > C:\Users\ARYA-PC\Desktop\output-transformed.glb [1.55MB] (2%)
Author: Grant Riley (https://sketchfab.com/grandriley)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/iron-man-69dde1ad49e94852984e3d83928efd65
Title: Iron Man
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function IronManModel(props : any) {
    const { nodes, materials } : any = useGLTF('/models/ironman/output-transformed.glb',true,true)
    return (
        <group {...props} onClick={() => props.setActiveView('initial')}>
            <mesh geometry={nodes.Object_2.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    )
}

useGLTF.preload('/models/ironman/output-transformed.glb',true,true)
