export const SkillsList = [
    {
        position: [0, 0, 0],
        glowColor: '#e34c26',
        title: 'HTML',
        textureURL: '/images/skills/html.png',
    },
    {
        position: [0, -40, 0],
        textPosition: [-16, 14, -32],
        glowColor: '#2965f1',
        title: 'CSS',
        textureURL: '/images/skills/css.png',
    },
    {
        position: [0, -80, 0],
        textPosition: [-16, 14, -16],
        glowColor: '#f7df1e',
        title: 'JavaScript',
        textureURL: '/images/skills/js.png',
    },
    {
        position: [0, -120, 0],
        textPosition: [-16, 14, -16],
        glowColor: '#3178c6',
        title: 'TypeScript',
        textureURL: '/images/skills/ts.png',
    },
    {
        position: [0, 0, 90],
        textPosition: [-16, 14, -28],
        glowColor: '#61dafb',
        title: 'React',
        textureURL: '/images/skills/react.png',
    },
    {
        position: [0, -40, 90],
        textPosition: [-16, 14, -22],
        glowColor: '#fff',
        title: 'NextJS',
        iconSize: [1.6, 1.6, 0],
        textureURL: '/images/skills/nextjs.png',
    },
    {
        position: [0, -80, 90],
        textPosition: [-16, 14, -21],
        glowColor: '#38bdf8',
        title: 'Tailwind',
        textureURL: '/images/skills/tailwind.png',
    },
    {
        position: [0, -120, 90],
        textPosition: [-16, 14, -19],
        glowColor: '#3c873a',
        title: 'Node JS',
        textureURL: '/images/skills/nodejs.png',
    },
    {
        position: [0, 0, 180],
        textPosition: [-16, 14, -20],
        glowColor: '#fff',
        title: 'Three JS',
        iconSize: [1.6, 1.6, 0],
        textureURL: '/images/skills/threejs.png',
    },
    {
        position: [0, -40, 180],
        textPosition: [-16, 14, -18],
        glowColor: '#facc15',
        title: 'JS Plugins',
        iconSize: [1.8, 1.8, 0],
        textureURL: '/images/skills/jsplugins.png',
    },
    {
        position: [0, -80, 180],
        textPosition: [-16, 14, -11],
        glowColor: '#ef4444',
        title: 'Fundamental',
        iconScale: 6,
        iconSize: [3.9, 1.9, 0],
        textureURL: '/images/skills/seo.png',
    },
]