/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 output.glb
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-srt-demon-sdc-54d229c2c0ff4eac8bc872f50b25e36c
Title: Dodge Challenger SRT DEMON SDC
*/

import React, {useMemo} from 'react'
import { useGLTF } from '@react-three/drei'
import {OptimizedMesh} from "@/component/OptimizedMesh";


export default function CarM1(props) {
    const { nodes, materials } = useGLTF('/models/dodge/optimized.glb',true,true)
    const meshes = useMemo(() => (
        <group {...props}>
            <OptimizedMesh castShadow geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} rotation={[-1.586, 0, 0]} scale={0.025} />
            <OptimizedMesh castShadow geometry={nodes.Object_5.geometry} material={materials.Carbone} rotation={[-1.586, 0, 0]} scale={0.025} />
            <OptimizedMesh castShadow geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} rotation={[-1.586, 0, 0]} scale={0.025} />
            <OptimizedMesh castShadow geometry={nodes.Object_53.geometry} material={materials.PaletteMaterial003} rotation={[-1.586, 0, 0]} scale={0.025} />
            <OptimizedMesh castShadow geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial004} rotation={[-1.586, 0, 0]} scale={0.025} />
        </group>
    ), [nodes, materials, props]);

    return meshes;
}

// useGLTF.preload('/models/dodge/output.glb',true,true)
useGLTF.preload('/models/dodge/optimized.glb',true,true)
