/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 output.glb
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-srt-demon-sdc-54d229c2c0ff4eac8bc872f50b25e36c
Title: Dodge Challenger SRT DEMON SDC
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import {LightRing} from "@/component/about/LightRing";


export default function CarM1(props) {
    const { nodes, materials } = useGLTF('/models/dodge/optimized.glb',true,true)
    return (
        <group {...props}>
            <mesh castShadow={true} geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} rotation={[-1.586, 0, 0]} scale={0.025} />
            <mesh castShadow={true} geometry={nodes.Object_5.geometry} material={materials.Carbone} rotation={[-1.586, 0, 0]} scale={0.025} />
            <mesh castShadow={true} geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} rotation={[-1.586, 0, 0]} scale={0.025} />
            <mesh castShadow={true} geometry={nodes.Object_53.geometry} material={materials.PaletteMaterial003} rotation={[-1.586, 0, 0]} scale={0.025} />
            <mesh castShadow={true} geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial004} rotation={[-1.586, 0, 0]} scale={0.025} />
            <mesh castShadow={true} geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial005} rotation={[-1.586, 0, 0]} scale={0.025} />
        </group>
    )
    // const { nodes, materials } = useGLTF('/models/dodge/output.glb',true,true)
    // return (
    //     <group {...props} >
    //         <group rotation={[-1.586, 0, 0]}>
    //             <group rotation={[Math.PI / 2, 0, 0]}>
    //                 <group  rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
    //                     <mesh castShadow={true} geometry={nodes.Object_4.geometry} material={materials.CARS} />
    //                     <mesh castShadow={true} geometry={nodes.Object_5.geometry} material={materials.Carbone} />
    //                 </group>
    //                 <group  rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
    //                     <mesh castShadow={true} geometry={nodes.Object_91.geometry} material={materials.GLASS} />
    //                     <mesh castShadow={true} geometry={nodes.Object_92.geometry} material={materials.tire} />
    //                     <mesh castShadow={true} geometry={nodes.Object_93.geometry} material={materials.material_16} />
    //                     <mesh castShadow={true} geometry={nodes.Object_94.geometry} material={materials.brakedisk} />
    //                     <mesh castShadow={true} geometry={nodes.Object_95.geometry} material={materials.rim_second} />
    //                 </group>
    //                 <mesh castShadow={true} geometry={nodes.Object_7.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_9.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_11.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_13.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_15.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_17.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_19.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_21.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_23.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_25.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_27.geometry} material={materials.mirror} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_29.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_31.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_33.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_35.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_37.geometry} material={materials.redglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_39.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_41.geometry} material={materials.redglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_43.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_45.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_47.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_49.geometry} material={materials.orangeglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_51.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_53.geometry} material={materials.lightglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_55.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_57.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_59.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_61.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_63.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_65.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_67.geometry} material={materials.carpaint_second} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_69.geometry} material={materials.GLSS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_71.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_73.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh geometry={nodes.Object_75.geometry} material={materials.GLSS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_77.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_79.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_81.geometry} material={materials.mattemetal} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_83.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_85.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_87.geometry} material={materials.interior} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_89.geometry} material={materials.interior} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_97.geometry} material={materials.CARS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_99.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_101.geometry} material={materials.CARS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_103.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_105.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    //                 <mesh castShadow={true} geometry={nodes.Object_107.geometry} material={materials.Carbone} position={[0, 1.814, 5.454]} scale={[1.37, 0.148, 0.024]} />
    //             </group>
    //         </group>
    //     </group>
    // )
}

// useGLTF.preload('/models/dodge/output.glb',true,true)
useGLTF.preload('/models/dodge/optimized.glb',true,true)
